### ISSUE TITLE
Pretrained checkpoints are missing

### ISSUE THREAD

**Issue by Ironman6666** [BoMingZhao/PNeRFLoc#3]
Hi author, tks for releasing the great work!

When I wanted to train the model of 7Scenes/stairs as your guide, I found that the checkpoints used during training are missing. I notice that you deleted them several months ago. Can you provide them again? Thank you very much!

**Comment by BoMingZhao** [comment]
Thanks for your 

> Hi author, tks for releasing the great work!
> 
> When I wanted to train the model of 7Scenes/stairs as your guide, I found that the checkpoints used during training are missing. I notice that you deleted them several months ago. Can you provide them again? Thank you very much!

Thanks for your interest in our work. Sorry for the mistake, this checkpoint is not using in the current model but still need to be loaded. I'll check my code version and update the code as soon as possible

**Comment by BoMingZhao** [comment]
Fix the bug

**Comment by Ironman6666** [comment]
> Fix the bug

Thank you so much!
