### ISSUE TITLE
Training error in 7Scenes/stairs.sh 

### ISSUE THREAD

**Issue by Ironman6666** [BoMingZhao/PNeRFLoc#4]

**Comment by Ironman6666** [comment]
Hello author, sorry to bother you again. I downloaded the latest checkpoint file you provided, and performed "bash. / dev_scripts/train / 7Scenes/stairs. sh" again. But there are still some mistakes that cause training to fail.
1. The debugging message shows that there are still some weights are not loaded.
![image](https://github.com/user-attachments/assets/fca884c4-77f9-4d16-bcf3-59bb68e78533)

2. Some iterations after starting training, "RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn" always appears. It seems to be relative to  the gradient. I tried several trainings  and found that each time  the iteration where this error occurred was not fixed.
![image](https://github.com/user-attachments/assets/7ad8957c-8c01-437d-a428-c6e8a09deb7a)
other attempt results
![image](https://github.com/user-attachments/assets/125a72e8-c706-42aa-b56f-5013016d2e58)

Can you give me some advice on these two problems? Thank you very much

**Comment by BoMingZhao** [comment]
> Hello author, sorry to bother you again. I downloaded the latest checkpoint file you provided, and performed "bash. / dev_scripts/train / 7Scenes/stairs. sh" again. But there are still some mistakes that cause training to fail.
> 
> 1. The debugging message shows that there are still some weights are not loaded.
>    ![image](https://private-user-images.githubusercontent.com/103632128/380430433-fca884c4-77f9-4d16-bcf3-59bb68e78533.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxODQxODUsIm5iZiI6MTczMDE4Mzg4NSwicGF0aCI6Ii8xMDM2MzIxMjgvMzgwNDMwNDMzLWZjYTg4NGM0LTc3ZjktNGQxNi1iY2YzLTU5YmI2OGU3ODUzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOVQwNjM4MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNGU3ZmIyOGU3YWI5OGQ5NzdkNjU3ZGIzNmIzNmIyZDFiZDI3ZmM1MWQ4YjYxOWRlMGMyZjQxNmU0Nzk5NzIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.RxOR7TMqaNs8NlAPOKU6fRaNhOb4XVJ4ZXgOsqHmVMA)
> 2. Some iterations after starting training, "RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn" always appears. It seems to be relative to  the gradient. I tried several trainings  and found that each time  the iteration where this error occurred was not fixed.
>    ![image](https://private-user-images.githubusercontent.com/103632128/380430497-7ad8957c-8c01-437d-a428-c6e8a09deb7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxODQxODUsIm5iZiI6MTczMDE4Mzg4NSwicGF0aCI6Ii8xMDM2MzIxMjgvMzgwNDMwNDk3LTdhZDg5NTdjLThjMDEtNDM3ZC1hNDI4LWM2ZThhMDlkZWI3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOVQwNjM4MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZWNiOTUwMDEwZjg2NTFhZDEyNzYxZTYwNGI0N2M0ODM3NWFmNTU3ZWY0YmE4MGE0MmJjZGQ2ZmNjMDc1MDc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0EBV1_7mPfJx3VckwPGaqXM42kgufpwQfq9m5Yo85wM)
>    other attempt results
>    ![image](https://private-user-images.githubusercontent.com/103632128/380430564-125a72e8-c706-42aa-b56f-5013016d2e58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxODQxODUsIm5iZiI6MTczMDE4Mzg4NSwicGF0aCI6Ii8xMDM2MzIxMjgvMzgwNDMwNTY0LTEyNWE3MmU4LWM3MDYtNDJhYS1iNTZmLTUwMTMwMTZkMmU1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOVQwNjM4MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mN2U0YTZmZjIxYWU3MzZjNWE5ZDU5NTEyODZjNzdkNGUyNmQ0ZDdmZmNlZDFmMjBmMzhlYWNmNGE1NmMxMmQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.bkBtArrDSFDXNczkIk4wRI3vzPh6yg0EN-_Nhu2_a7s)
> 
> Can you give me some advice on these two problems? Thank you very much

Sorry for the late reply. I’m currently preparing to go aboard and I’ll check the issue tonight.

**Comment by BoMingZhao** [comment]
> Hello author, sorry to bother you again. I downloaded the latest checkpoint file you provided, and performed "bash. / dev_scripts/train / 7Scenes/stairs. sh" again. But there are still some mistakes that cause training to fail.
> 
> 1. The debugging message shows that there are still some weights are not loaded.
>    ![image](https://private-user-images.githubusercontent.com/103632128/380430433-fca884c4-77f9-4d16-bcf3-59bb68e78533.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMjMwNTIsIm5iZiI6MTczMDIyMjc1MiwicGF0aCI6Ii8xMDM2MzIxMjgvMzgwNDMwNDMzLWZjYTg4NGM0LTc3ZjktNGQxNi1iY2YzLTU5YmI2OGU3ODUzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOVQxNzI1NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MjZiMjc5Nzg5OGIyMmY1ZTlkMWZmZDZhZjA3OGQ0ODEyYmJhODdmYTQ2MTY5NWZhZmQ0NGYwZjZjNGNmYzA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5p2AA_9Bgtk9u0TxAPA4_nltsmxU6LpIJiChgu-aeko)
> 2. Some iterations after starting training, "RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn" always appears. It seems to be relative to  the gradient. I tried several trainings  and found that each time  the iteration where this error occurred was not fixed.
>    ![image](https://private-user-images.githubusercontent.com/103632128/380430497-7ad8957c-8c01-437d-a428-c6e8a09deb7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMjMwNTIsIm5iZiI6MTczMDIyMjc1MiwicGF0aCI6Ii8xMDM2MzIxMjgvMzgwNDMwNDk3LTdhZDg5NTdjLThjMDEtNDM3ZC1hNDI4LWM2ZThhMDlkZWI3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOVQxNzI1NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Mzk4NDNlMDM5MGI5MjE2ZDk3NDIyMDAyY2YwYmVkNWE5MWEwODk4MzVkMDkzODZhOWU5OThhZGE5OWI5MDk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GfEntM4fpIlD076MTDK_ceEIo9lplBockRbLfQFhgsw)
>    other attempt results
>    ![image](https://private-user-images.githubusercontent.com/103632128/380430564-125a72e8-c706-42aa-b56f-5013016d2e58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMjMwNTIsIm5iZiI6MTczMDIyMjc1MiwicGF0aCI6Ii8xMDM2MzIxMjgvMzgwNDMwNTY0LTEyNWE3MmU4LWM3MDYtNDJhYS1iNTZmLTUwMTMwMTZkMmU1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOVQxNzI1NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NTEzM2FjZjYxMmM0Y2QxN2EzMDNmMjU4ODE4MDZhZTk3MWU5YWRiZWNiODA2ZTI3YzQ0ZWIwNzI3YTg5N2MwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.g-ENmREz6IEMEi0U-KB_ZICocdHdf5ohlMGoYM_zJ3A)
> 
> Can you give me some advice on these two problems? Thank you very much

Hi, I run the same code and there is no bug on my case.

> The debugging message shows that there are still some weights are not loaded.
That means you don't have a trained checkpoints to load, which is correct in your training process. Have you ever change the training script file?

**Comment by BoMingZhao** [comment]
Hi, I run the same code and there is no bug on my case.

>The debugging message shows that there are still some weights are not loaded.


That means you don't have a trained checkpoints to load, which is correct in your training process. Have you ever change the training script file?

**Comment by BoMingZhao** [comment]
Long time no activation. Free to open again
